import {Component, EventEmitter, Input, OnDestroy, OnInit, Output} from '@angular/core';
import * as _ from 'lodash';
import {getAutoGeneratedLegends} from 'src/app/core/helpers/get-auto-generated-legend-sets.helper';

import * as legendHelper from '../../helpers';
import {ARROW_DOWN_ICON} from '../../icons/arrow-down.icon';
import {Legend, LegendSet} from '../../models/legend-set';

@Component({
  selector: 'app-legend-set-container',
  templateUrl: './legend-set-container.component.html',
  styleUrls: ['./legend-set-container.component.css'],
})
export class LegendSetContainerComponent implements OnInit, OnDestroy {
  @Input()
  legendSetEntities;
  @Input()
  showDeleteIcon: boolean;
  @Input()
  legendItems: LegendSet[];
  @Input()
  legendSetLoaded;

  @Output()
  legendSetConfigurationClose: EventEmitter<any> = new EventEmitter();

  @Output()
  legendSetConfigurationUpdate: EventEmitter<any> = new EventEmitter();
  legendSets: LegendSet[];
  currentLegendSet: string;
  arrowDownIcon: string;

  constructor() {
    this.currentLegendSet = '';
    this.arrowDownIcon = ARROW_DOWN_ICON;
  }

  ngOnInit() {
    const legendSets: LegendSet[] = this.legendSetEntities;

    this.currentLegendSet =
      legendSets && legendSets.length > 0 ? legendSets[0].id : '';

    this.legendSets = _.map(legendSets, (legendSet: LegendSet) => {
      return {
        ...legendSet,
        legends:
          legendSet.legends.length > 0
            ? legendSet.legends
            : getAutoGeneratedLegends(),
      };
    });
  }

  addNotApplicableLegendStatus(legends, defaultObj) {
    let localLegends = [];
    localLegends = legends;
    const notApplicableIndex = _.findLastIndex(defaultObj, (legendObj) => {
      return legendObj['name'] === 'N/A';
    });

    const leg = {
      id: 'RFKK007nOS9',
      name: 'High',
      color: '#3eef9c',
      endValue: 100,
      startValue: 61,
    };

    if (!_.some(legends, {name: 'N/A'})) {
      localLegends.push(defaultObj[notApplicableIndex]);
    }
    return localLegends;
  }

  onSetCurrentLegendSet(legendSet: LegendSet, event) {
    event.stopPropagation();
    this.currentLegendSet =
      legendSet && legendSet.id
        ? legendSet.id === this.currentLegendSet
          ? ''
          : legendSet.id
        : this.currentLegendSet;
  }

  addNewLegend(event, legendSetId?: string) {
    event.stopPropagation();
    const legendSet = legendSetId ? _.find(this.legendSets, ['id', legendSetId]) : _.head(this.legendSets);
    const {legends} = legendSet;
    const legend: Legend = legendHelper.getNewLegend(legends);
    legendSet.legends = _.sortBy([...legends, legend], 'startValue');
  }

  trackByFn(index, item) {
    return item && item.id ? item.id : index;
  }

  onLegendSetUpdates(updatedLegendSet) {
    this.legendSets =
      this.legendSets.length < 0 ? this.legendSetEntities : this.legendSets;
    const updatedLegendSets = _.map(this.legendSets, (legendSet) => {
      if (legendSet.id == updatedLegendSet.id) {
        return updatedLegendSet;
      } else {
        return legendSet;
      }
    });
    this.legendSets = updatedLegendSets;
  }

  onUpdate(event) {
    event.stopPropagation();
    this.legendSetConfigurationUpdate.emit(this.legendSets);
  }

  onClose(e) {
    e.stopPropagation();
    this.legendSetConfigurationClose.emit(this.legendSets);
  }

  ngOnDestroy() {
    this.legendSetConfigurationClose.emit(this.legendSets);
  }
}
