import { generateUid } from './generate-uid.helper';
import { getFormattedDate } from './generate-formatted-date.helper';
import { programId, programStage } from '../constants/program-items.constant';
import * as _ from 'lodash';
export function generateEvent(actionTrackerDataItem, eventDataValues?) {
  console.log('Here CHANGING');
  return {
    event: generateUid(), // autogenerated
    dataValues: eventDataValues,
    program: programId, //const
    programStage: programStage, //const
    orgUnit: _.get(actionTrackerDataItem, 'selectionParams.orgUnit'),
    trackedEntityInstance:
      actionTrackerDataItem.id || actionTrackerDataItem.trackedEntityInstance,
    status: 'ACTIVE',
    eventDate: _.get(actionTrackerDataItem, 'selectionParams.eventDate')
  };
}
