import { generateUid } from './generate-uid.helper';
import { getFormattedDate } from './generate-formatted-date.helper';
import { programId, programStage } from '../constants/program-items.constant';
import * as _ from 'lodash';
export function generateEvent(
  actionTrackingItem,
  eventId,
  eventDate,
  isNewEvent,
  newDataValuesArray
) {
  return {
    event: isNewEvent ? generateUid() : eventId, // autogenerated
    dataValues: newDataValuesArray,
    program: programId, //const
    programStage: programStage, //const
    orgUnit: _.get(actionTrackingItem, 'orgUnit'),
    trackedEntityInstance:
      actionTrackingItem.id || actionTrackingItem.trackedEntityInstance,
    status: 'ACTIVE',
    eventDate: eventDate
  };
}
