import { generateUid } from './generate-uid.helper';
import { programId, programStage } from '../constants/program-items.constant';
import * as _ from 'lodash';
export function generateEvent(actionTrackingItem, eventData, isNewEvent?) {
  return {
    event: isNewEvent ? generateUid() : eventData.eventId, // autogenerated
    dataValues: eventData.eventDataValues,
    program: programId, //const
    programStage: programStage, //const
    orgUnit: _.get(actionTrackingItem, 'orgUnit'),
    trackedEntityInstance:
      actionTrackingItem.id || actionTrackingItem.trackedEntityInstance,
    status: 'ACTIVE',
    eventDate: eventData.eventDate
  };
}
