import * as _ from 'lodash';
import { generateUid } from './generate-uid.helper';
import { getFormattedDate } from './generate-formatted-date.helper';
import {
  programId,
  trackedEntityType,
  programStage
} from '../constants/program-items.constant';
export function generateTEI(actionTrackerDataItem) {
  const trackedEntityInstance = generateUid();
  return {
    rootCauseDataId: _.get(
      actionTrackerDataItem,
      'selectionParams.rootCauseDataId'
    ),
    trackedEntityInstance: actionTrackerDataItem.id || trackedEntityInstance, // if not there autogen
    trackedEntityType: trackedEntityType,
    orgUnit: _.get(actionTrackerDataItem, 'selectionParams.orgUnit'),
    attributes: _.get(actionTrackerDataItem, 'attributes'),
    enrollments: actionTrackerDataItem.enrollments || [
      {
        trackedEntityInstance:
          actionTrackerDataItem.id || trackedEntityInstance, // if not there autogen
        program: programId,
        status: 'ACTIVE',
        orgUnit: _.get(actionTrackerDataItem, 'selectionParams.orgUnit'),
        enrollmentDate: getFormattedDate(), //todays date
        incidentDate: getFormattedDate(), //todays date
        enrollment: generateUid(), // autogenerated
        events: [
          {
            event: generateUid(), // autogenerated
            dataValues: _.get(actionTrackerDataItem, 'dataValues'),
            program: programId, //const
            programStage: programStage, //const
            orgUnit: _.get(actionTrackerDataItem, 'selectionParams.orgUnit'),
            trackedEntityInstance:
              actionTrackerDataItem.id || trackedEntityInstance,
            status: 'ACTIVE',
            eventDate: _.get(actionTrackerDataItem, 'selectionParams.eventDate')
          }
        ]
      }
    ]
  };
}
