export const defaultActionTrackerProgram: any = {
  trackedEntityAttributes: [
    {
      lastUpdated: '2020-01-25T11:40:54.562',
      id: 'Ua9aBlFUHXb',
      created: '2020-01-17T10:27:34.341',
      name: 'Designation Title',
      shortName: 'Designation Title',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      attributeValues: [],
      userAccesses: [],
      legendSets: []
    },
    {
      code: 'BNA_REF',
      lastUpdated: '2020-01-25T11:40:54.564',
      id: 'blOw6mjuv6j',
      created: '2020-01-14T13:01:24.759',
      name: 'BNA Reference',
      shortName: 'BNA Reference',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      attributeValues: [],
      userAccesses: [],
      legendSets: []
    },
    {
      lastUpdated: '2020-01-25T11:40:54.565',
      id: 'dhr6wl8F7So',
      created: '2020-01-14T13:12:54.907',
      name: 'Action Description',
      shortName: 'Action Description',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'LONG_TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      attributeValues: [],
      userAccesses: [],
      legendSets: []
    },
    {
      lastUpdated: '2020-02-10T16:39:07.654',
      id: 'qTXUUntafIX',
      created: '2020-01-17T10:25:43.795',
      name: 'Start Date',
      shortName: 'Start Date',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'DATE',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          lastUpdated: '2020-01-28T14:37:57.793',
          created: '2020-01-28T14:37:57.793',
          value: 'true',
          attribute: { id: 'e444SAZc6Qg' }
        }
      ],
      userAccesses: [],
      legendSets: []
    },
    {
      lastUpdated: '2020-02-04T18:20:20.784',
      id: 'P7qIYtQIeoK',
      created: '2020-01-28T14:15:20.022',
      name: 'Budget',
      shortName: 'Budget',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          lastUpdated: '2020-02-04T18:20:20.765',
          created: '2020-02-04T18:20:20.765',
          value: 'true',
          attribute: { id: 'ryc6MHoA88m' }
        }
      ],
      userAccesses: [],
      legendSets: []
    },
    {
      lastUpdated: '2020-02-04T18:20:05.188',
      id: 'knMPFmtAM29',
      created: '2020-01-28T14:16:03.805',
      name: 'BNA Target',
      shortName: 'BNA Target',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'NUMBER',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          lastUpdated: '2020-02-04T18:20:05.166',
          created: '2020-02-04T18:20:05.166',
          value: 'true',
          attribute: { id: 'ryc6MHoA88m' }
        }
      ],
      userAccesses: [],
      legendSets: []
    },
    {
      lastUpdated: '2020-02-10T16:39:35.575',
      id: 'ge6NMvlcYx5',
      created: '2020-02-10T16:39:30.327',
      name: 'End Date',
      shortName: 'End Date',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'DATE',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          lastUpdated: '2020-01-28T14:37:57.793',
          created: '2020-01-28T14:37:57.793',
          value: 'false',
          attribute: { id: 'e444SAZc6Qg' }
        }
      ],
      userAccesses: [],
      legendSets: []
    },
    {
      lastUpdated: '2020-01-25T11:40:54.567',
      id: 'AuW5NppdH5e',
      created: '2020-01-17T10:27:00.323',
      name: 'Responsible Person',
      shortName: 'Responsible Person',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      attributeValues: [],
      userAccesses: [],
      legendSets: []
    }
  ],
  categoryCombos: [
    {
      code: 'default',
      created: '2019-01-17T15:04:27.377',
      lastUpdated: '2019-01-17T15:04:27.404',
      name: 'default',
      id: 'bjDvmb4bfuf',
      dataDimensionType: 'DISAGGREGATION',
      publicAccess: 'rw------',
      skipTotal: false,
      userGroupAccesses: [],
      translations: [],
      userAccesses: [],
      categories: [{ id: 'GLevLNI9wkl' }]
    }
  ],
  programTrackedEntityAttributes: [
    {
      created: '2020-02-10T16:40:31.649',
      lastUpdated: '2020-02-10T16:41:17.452',
      id: 'UPiRHleMEsi',
      mandatory: false,
      searchable: false,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 4,
      program: { id: 'ROSaojkGieB' },
      trackedEntityAttribute: { id: 'ge6NMvlcYx5' },
      programTrackedEntityAttributeGroups: []
    },
    {
      created: '2020-01-20T07:03:58.483',
      lastUpdated: '2020-02-10T16:41:17.452',
      id: 'LecLymPquue',
      mandatory: false,
      searchable: true,
      renderOptionsAsRadio: false,
      displayInList: false,
      sortOrder: 1,
      program: { id: 'ROSaojkGieB' },
      trackedEntityAttribute: { id: 'blOw6mjuv6j' },
      programTrackedEntityAttributeGroups: []
    },
    {
      created: '2020-01-20T07:03:58.483',
      lastUpdated: '2020-02-10T16:41:17.453',
      id: 'XajRri3534V',
      mandatory: false,
      searchable: false,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 5,
      program: { id: 'ROSaojkGieB' },
      trackedEntityAttribute: { id: 'AuW5NppdH5e' },
      programTrackedEntityAttributeGroups: []
    },
    {
      created: '2020-01-28T14:16:43.909',
      lastUpdated: '2020-02-10T16:41:17.453',
      id: 'xh38fmO5BmB',
      mandatory: false,
      searchable: true,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 7,
      program: { id: 'ROSaojkGieB' },
      trackedEntityAttribute: { id: 'P7qIYtQIeoK' },
      programTrackedEntityAttributeGroups: []
    },
    {
      created: '2020-01-28T14:16:43.909',
      lastUpdated: '2020-02-10T16:41:17.453',
      id: 'hUaP4U5Wwvj',
      mandatory: false,
      searchable: true,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 8,
      program: { id: 'ROSaojkGieB' },
      trackedEntityAttribute: { id: 'knMPFmtAM29' },
      programTrackedEntityAttributeGroups: []
    },
    {
      created: '2020-01-20T07:03:58.483',
      lastUpdated: '2020-02-10T16:41:17.452',
      id: 'DfT0JC0VKA3',
      mandatory: false,
      searchable: false,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 2,
      program: { id: 'ROSaojkGieB' },
      trackedEntityAttribute: { id: 'dhr6wl8F7So' },
      programTrackedEntityAttributeGroups: []
    },
    {
      created: '2020-01-20T07:03:58.483',
      lastUpdated: '2020-02-10T16:41:17.452',
      id: 'ydN3ekUUT2m',
      mandatory: false,
      searchable: false,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 3,
      program: { id: 'ROSaojkGieB' },
      trackedEntityAttribute: { id: 'qTXUUntafIX' },
      programTrackedEntityAttributeGroups: []
    },
    {
      created: '2020-01-20T07:03:58.483',
      lastUpdated: '2020-02-10T16:41:17.453',
      id: 'fzISmkQRgcb',
      mandatory: false,
      searchable: false,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 6,
      program: { id: 'ROSaojkGieB' },
      trackedEntityAttribute: { id: 'Ua9aBlFUHXb' },
      programTrackedEntityAttributeGroups: []
    }
  ],
  programStages: [
    {
      lastUpdated: '2020-01-25T11:40:54.654',
      id: 'TppfLBfs95i',
      created: '2020-01-20T07:03:58.508',
      name: 'Action Status',
      allowGenerateNextVisit: false,
      executionDateLabel: 'Review Date',
      preGenerateUID: false,
      publicAccess: 'rw------',
      openAfterEnrollment: false,
      repeatable: true,
      remindCompleted: false,
      displayGenerateEventBox: true,
      generatedByEnrollmentDate: false,
      validationStrategy: 'ON_COMPLETE',
      autoGenerateEvent: true,
      sortOrder: 1,
      hideDueDate: true,
      blockEntryForm: false,
      minDaysFromStart: 0,
      program: { id: 'ROSaojkGieB' },
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      notificationTemplates: [],
      programStageDataElements: [
        {
          lastUpdated: '2020-01-25T11:40:54.658',
          id: 'kmzE1H2Vc2b',
          created: '2020-01-20T07:03:58.509',
          displayInReports: true,
          skipSynchronization: false,
          externalAccess: false,
          renderOptionsAsRadio: false,
          allowFutureDate: false,
          compulsory: false,
          allowProvidedElsewhere: false,
          sortOrder: 1,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true
          },
          programStage: { id: 'TppfLBfs95i' },
          dataElement: { id: 'DRFRXS9YGDw' },
          favorites: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: []
        },
        {
          lastUpdated: '2020-01-25T11:40:54.656',
          id: 'Y4OIrJp8WOA',
          created: '2020-01-20T07:03:58.508',
          displayInReports: true,
          skipSynchronization: false,
          externalAccess: false,
          renderOptionsAsRadio: false,
          allowFutureDate: false,
          compulsory: false,
          allowProvidedElsewhere: false,
          sortOrder: 2,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true
          },
          programStage: { id: 'TppfLBfs95i' },
          dataElement: { id: 'D8uK000mWtr' },
          favorites: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: []
        }
      ],
      translations: [],
      userGroupAccesses: [],
      attributeValues: [],
      userAccesses: [],
      programStageSections: []
    }
  ],
  attributes: [
    {
      lastUpdated: '2020-01-27T14:31:47.110',
      id: 'GvW2Wtw6L5l',
      created: '2020-01-27T14:31:47.110',
      name: 'hasLegend',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: true,
      constantAttribute: false,
      valueType: 'BOOLEAN',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: false,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: false,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      userAccesses: []
    },
    {
      lastUpdated: '2020-01-28T08:39:15.804',
      id: 'GOcsBWoi35g',
      created: '2020-01-28T08:39:15.804',
      name: 'isActionStatus',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: true,
      constantAttribute: false,
      valueType: 'BOOLEAN',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: false,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: false,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      userAccesses: []
    },
    {
      lastUpdated: '2020-01-28T14:37:16.271',
      id: 'e444SAZc6Qg',
      created: '2020-01-28T14:37:16.271',
      name: 'isRangePeriod',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: false,
      constantAttribute: false,
      valueType: 'BOOLEAN',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: true,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: false,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      userAccesses: []
    },
    {
      lastUpdated: '2020-02-04T18:19:51.115',
      id: 'ryc6MHoA88m',
      created: '2020-02-04T18:19:51.115',
      name: 'isActionTrackingColumn',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: false,
      constantAttribute: false,
      valueType: 'TRUE_ONLY',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: true,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: false,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      userAccesses: []
    }
  ],
  programStageDataElements: [
    {
      created: '2020-01-20T07:03:58.509',
      lastUpdated: '2020-01-25T11:40:54.658',
      id: 'kmzE1H2Vc2b',
      displayInReports: true,
      skipSynchronization: false,
      renderOptionsAsRadio: false,
      compulsory: false,
      allowProvidedElsewhere: false,
      sortOrder: 1,
      allowFutureDate: false,
      programStage: { id: 'TppfLBfs95i' },
      dataElement: { id: 'DRFRXS9YGDw' }
    },
    {
      created: '2020-01-20T07:03:58.508',
      lastUpdated: '2020-01-25T11:40:54.656',
      id: 'Y4OIrJp8WOA',
      displayInReports: true,
      skipSynchronization: false,
      renderOptionsAsRadio: false,
      compulsory: false,
      allowProvidedElsewhere: false,
      sortOrder: 2,
      allowFutureDate: false,
      programStage: { id: 'TppfLBfs95i' },
      dataElement: { id: 'D8uK000mWtr' }
    }
  ],
  trackedEntityTypes: [
    {
      created: '2020-01-14T12:54:33.736',
      lastUpdated: '2020-01-25T11:40:54.504',
      name: 'Action',
      id: 'WQLx9VNVeZU',
      publicAccess: 'rw------',
      description: 'Action Item',
      maxTeiCountToReturn: 0,
      allowAuditLog: false,
      featureType: 'NONE',
      minAttributesRequiredToSearch: 1,
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      userGroupAccesses: [],
      attributeValues: [],
      trackedEntityTypeAttributes: [],
      translations: [],
      userAccesses: []
    }
  ],
  categories: [
    {
      code: 'default',
      created: '2019-01-17T15:04:27.362',
      lastUpdated: '2019-02-19T08:20:34.252',
      name: 'default',
      id: 'GLevLNI9wkl',
      dataDimensionType: 'DISAGGREGATION',
      publicAccess: 'rw------',
      dataDimension: false,
      userGroupAccesses: [],
      attributeValues: [],
      translations: [],
      userAccesses: [],
      categoryOptions: [{ id: 'xYerKDKCefk' }]
    }
  ],
  dataElements: [
    {
      lastUpdated: '2020-01-28T08:39:26.077',
      id: 'DRFRXS9YGDw',
      created: '2020-01-17T05:37:32.442',
      name: 'Action Tracker : Action Status',
      shortName: 'Action Tracker : Action Status',
      aggregationType: 'NONE',
      domainType: 'TRACKER',
      publicAccess: 'rw------',
      description: 'Field to capture the status of the action execution',
      valueType: 'TEXT',
      formName: 'Action Status',
      zeroIsSignificant: false,
      categoryCombo: { id: 'bjDvmb4bfuf' },
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          lastUpdated: '2020-01-28T08:39:26.041',
          created: '2020-01-28T08:39:26.041',
          value: 'true',
          attribute: { id: 'GOcsBWoi35g' }
        },
        {
          lastUpdated: '2020-01-27T14:32:07.168',
          created: '2020-01-27T14:32:07.168',
          value: 'true',
          attribute: { id: 'GvW2Wtw6L5l' }
        }
      ],
      userAccesses: [],
      legendSets: [],
      aggregationLevels: []
    },
    {
      lastUpdated: '2020-01-25T11:40:54.445',
      id: 'D8uK000mWtr',
      created: '2020-01-17T05:39:31.272',
      name: 'Action Tracker : Comments',
      shortName: 'Action Tracker : Comments',
      aggregationType: 'NONE',
      domainType: 'TRACKER',
      publicAccess: 'rw------',
      description: 'Field to capture the action comments',
      valueType: 'LONG_TEXT',
      formName: 'Action Comments',
      zeroIsSignificant: false,
      categoryCombo: { id: 'bjDvmb4bfuf' },
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      user: { id: 'M5zQapPyTZI' },
      translations: [],
      userGroupAccesses: [],
      attributeValues: [],
      userAccesses: [],
      legendSets: [],
      aggregationLevels: []
    }
  ],
  categoryOptions: [
    {
      code: 'default',
      created: '2019-01-17T15:04:27.241',
      lastUpdated: '2019-01-17T15:04:27.413',
      name: 'default',
      id: 'xYerKDKCefk',
      publicAccess: 'rwrw----',
      userGroupAccesses: [],
      attributeValues: [],
      translations: [],
      userAccesses: [],
      organisationUnits: []
    }
  ],
  categoryOptionCombos: [
    {
      lastUpdated: '2019-01-17T15:04:27.401',
      code: 'default',
      created: '2019-01-17T15:04:27.393',
      name: 'default',
      id: 'HllvX50cXC0',
      ignoreApproval: false,
      categoryCombo: { id: 'bjDvmb4bfuf' },
      translations: [],
      attributeValues: [],
      categoryOptions: [{ id: 'xYerKDKCefk' }]
    }
  ],
  programs: [
    {
      lastUpdated: '2020-02-10T16:41:17.451',
      id: 'ROSaojkGieB',
      created: '2020-01-20T07:03:58.524',
      name: 'Action Tracker v1',
      shortName: 'Action Tracker v1',
      publicAccess: 'rw------',
      completeEventsExpiryDays: 0,
      ignoreOverdueEvents: false,
      skipOffline: false,
      minAttributesRequiredToSearch: 1,
      displayFrontPageList: true,
      onlyEnrollOnce: true,
      programType: 'WITH_REGISTRATION',
      accessLevel: 'OPEN',
      version: 10,
      maxTeiCountToReturn: 0,
      selectIncidentDatesInFuture: false,
      displayIncidentDate: false,
      selectEnrollmentDatesInFuture: false,
      expiryDays: 0,
      useFirstStageDuringRegistration: false,
      categoryCombo: { id: 'bjDvmb4bfuf' },
      lastUpdatedBy: { id: 'M5zQapPyTZI' },
      trackedEntityType: { id: 'WQLx9VNVeZU' },
      user: { id: 'M5zQapPyTZI' },
      programTrackedEntityAttributes: [
        {
          lastUpdated: '2020-02-10T16:41:17.452',
          id: 'LecLymPquue',
          created: '2020-01-20T07:03:58.483',
          name: 'Action Tracker v1 BNA Reference',
          displayName: 'Action Tracker v1 BNA Reference',
          mandatory: false,
          displayShortName: 'Action Tracker v1 BNA Reference',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'TEXT',
          searchable: true,
          displayInList: false,
          sortOrder: 1,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true
          },
          program: { id: 'ROSaojkGieB' },
          trackedEntityAttribute: { id: 'blOw6mjuv6j' },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: []
        },
        {
          lastUpdated: '2020-02-10T16:41:17.452',
          id: 'DfT0JC0VKA3',
          created: '2020-01-20T07:03:58.483',
          name: 'Action Tracker v1 Action Description',
          displayName: 'Action Tracker v1 Action Description',
          mandatory: false,
          displayShortName: 'Action Tracker v1 Action Description',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'LONG_TEXT',
          searchable: false,
          displayInList: true,
          sortOrder: 2,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true
          },
          program: { id: 'ROSaojkGieB' },
          trackedEntityAttribute: { id: 'dhr6wl8F7So' },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: []
        },
        {
          lastUpdated: '2020-02-10T16:41:17.452',
          id: 'ydN3ekUUT2m',
          created: '2020-01-20T07:03:58.483',
          name: 'Action Tracker v1 Start Date',
          displayName: 'Action Tracker v1 Start Date',
          mandatory: false,
          displayShortName: 'Action Tracker v1 Start Date',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'DATE',
          searchable: false,
          displayInList: true,
          sortOrder: 3,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true
          },
          program: { id: 'ROSaojkGieB' },
          trackedEntityAttribute: { id: 'qTXUUntafIX' },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: []
        },
        {
          lastUpdated: '2020-02-10T16:41:17.452',
          id: 'UPiRHleMEsi',
          created: '2020-02-10T16:40:31.649',
          name: 'Action Tracker v1 End Date',
          displayName: 'Action Tracker v1 End Date',
          mandatory: false,
          displayShortName: 'Action Tracker v1 End Date',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'DATE',
          searchable: false,
          displayInList: true,
          sortOrder: 4,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true
          },
          program: { id: 'ROSaojkGieB' },
          trackedEntityAttribute: { id: 'ge6NMvlcYx5' },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: []
        },
        {
          lastUpdated: '2020-02-10T16:41:17.453',
          id: 'XajRri3534V',
          created: '2020-01-20T07:03:58.483',
          name: 'Action Tracker v1 Responsible Person',
          displayName: 'Action Tracker v1 Responsible Person',
          mandatory: false,
          displayShortName: 'Action Tracker v1 Responsible Person',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'TEXT',
          searchable: false,
          displayInList: true,
          sortOrder: 5,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true
          },
          program: { id: 'ROSaojkGieB' },
          trackedEntityAttribute: { id: 'AuW5NppdH5e' },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: []
        },
        {
          lastUpdated: '2020-02-10T16:41:17.453',
          id: 'fzISmkQRgcb',
          created: '2020-01-20T07:03:58.483',
          name: 'Action Tracker v1 Designation Title',
          displayName: 'Action Tracker v1 Designation Title',
          mandatory: false,
          displayShortName: 'Action Tracker v1 Designation Title',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'TEXT',
          searchable: false,
          displayInList: true,
          sortOrder: 6,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true
          },
          program: { id: 'ROSaojkGieB' },
          trackedEntityAttribute: { id: 'Ua9aBlFUHXb' },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: []
        },
        {
          lastUpdated: '2020-02-10T16:41:17.453',
          id: 'xh38fmO5BmB',
          created: '2020-01-28T14:16:43.909',
          name: 'Action Tracker v1 Budget',
          displayName: 'Action Tracker v1 Budget',
          mandatory: false,
          displayShortName: 'Action Tracker v1 Budget',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'TEXT',
          searchable: true,
          displayInList: true,
          sortOrder: 7,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true
          },
          program: { id: 'ROSaojkGieB' },
          trackedEntityAttribute: { id: 'P7qIYtQIeoK' },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: []
        },
        {
          lastUpdated: '2020-02-10T16:41:17.453',
          id: 'hUaP4U5Wwvj',
          created: '2020-01-28T14:16:43.909',
          name: 'Action Tracker v1 BNA Target',
          displayName: 'Action Tracker v1 BNA Target',
          mandatory: false,
          displayShortName: 'Action Tracker v1 BNA Target',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'NUMBER',
          searchable: true,
          displayInList: true,
          sortOrder: 8,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true
          },
          program: { id: 'ROSaojkGieB' },
          trackedEntityAttribute: { id: 'knMPFmtAM29' },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: []
        }
      ],
      notificationTemplates: [],
      translations: [],
      userGroupAccesses: [],
      programSections: [],
      attributeValues: [],
      programStages: [{ id: 'TppfLBfs95i' }],
      userAccesses: []
    }
  ]
};
