export const defaultActionTrackerProgram: any = {
  attributes: [
    {
      id: 'xsOK0ms8YJv',
      name: 'columnMandatory',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: true,
      constantAttribute: false,
      valueType: 'BOOLEAN',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: true,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: true,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,
    },
    {
      id: 'GvW2Wtw6L5l',
      name: 'hasLegend',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: true,
      constantAttribute: false,
      valueType: 'BOOLEAN',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: false,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: false,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,
    },
    {
      id: 'GOcsBWoi35g',
      name: 'isActionStatus',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: true,
      constantAttribute: false,
      valueType: 'BOOLEAN',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: false,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: false,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,
    },
    {
      id: 'e444SAZc6Qg',
      name: 'isRangePeriod',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: false,
      constantAttribute: false,
      valueType: 'BOOLEAN',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: true,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: false,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,
    },
    {
      id: 'ryc6MHoA88m',
      name: 'isActionTrackingColumn',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: false,
      constantAttribute: false,
      valueType: 'TRUE_ONLY',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: true,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: false,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,
    },
  ],
  userGroups: [
    {
      code: 'ACTION_TRACKER_USERS',
      name: 'Action Tracker users',
      id: 't7Gi00eBwdQ',
      publicAccess: 'rw------',
    },
  ],
  trackedEntityTypes: [
    {
      name: 'Action',
      id: 'WQLx9VNVeZU',
      publicAccess: 'rwrw----',
      description: 'Action Item',
      maxTeiCountToReturn: 0,
      allowAuditLog: false,
      featureType: 'NONE',
      minAttributesRequiredToSearch: 1,
    },
  ],
  trackedEntityAttributes: [
    {
      id: 'Ua9aBlFUHXb',
      name: 'Designation Title',
      shortName: 'Designation Title',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
    },
    {
      code: 'BNA_REF',
      id: 'blOw6mjuv6j',
      name: 'BNA Reference',
      shortName: 'BNA Reference',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
    },
    {
      id: 'dhr6wl8F7So',
      name: 'Action Description',
      shortName: 'Action Description',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'LONG_TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
    },
    {
      id: 'qTXUUntafIX',
      name: 'Start Date',
      shortName: 'Start Date',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'DATE',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'e444SAZc6Qg',
          },
        },
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
    },
    {
      id: 'P7qIYtQIeoK',
      name: 'Budget',
      shortName: 'Budget',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'INTEGER_POSITIVE',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'ryc6MHoA88m',
          },
        },
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
    },
    {
      id: 'knMPFmtAM29',
      name: 'BNA Target',
      shortName: 'BNA Target',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'NUMBER',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'ryc6MHoA88m',
          },
        },
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
    },
    {
      id: 'ge6NMvlcYx5',
      name: 'End Date',
      shortName: 'End Date',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'DATE',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      attributeValues: [
        {
          value: 'false',
          attribute: {
            id: 'e444SAZc6Qg',
          },
        },
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
    },
    {
      id: 'AuW5NppdH5e',
      name: 'Responsible Person',
      shortName: 'Responsible Person',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
    },
  ],

  dataElements: [
    {
      id: 'DRFRXS9YGDw',
      name: 'Action Tracker : Action Status',
      shortName: 'Action Tracker : Action Status',
      aggregationType: 'NONE',
      domainType: 'TRACKER',
      publicAccess: 'rw------',
      description: 'Field to capture the status of the action execution',
      valueType: 'TEXT',
      formName: 'Action Status',
      zeroIsSignificant: false,
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'GOcsBWoi35g',
          },
        },
        {
          value: 'true',
          attribute: {
            id: 'GvW2Wtw6L5l',
          },
        },
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
    },
    {
      id: 'D8uK000mWtr',
      name: 'Action Tracker : Comments',
      shortName: 'Action Tracker : Comments',
      aggregationType: 'NONE',
      domainType: 'TRACKER',
      publicAccess: 'rw------',
      description: 'Field to capture the action comments',
      valueType: 'LONG_TEXT',
      formName: 'Action Comments',
      zeroIsSignificant: false,
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
    },
  ],
  programStages: [
    {
      id: 'TppfLBfs95i',
      name: 'Action Status',
      allowGenerateNextVisit: false,
      executionDateLabel: 'Review Date',
      preGenerateUID: false,
      publicAccess: '--r-----',
      openAfterEnrollment: false,
      repeatable: true,
      remindCompleted: false,
      displayGenerateEventBox: true,
      generatedByEnrollmentDate: false,
      validationStrategy: 'ON_COMPLETE',
      autoGenerateEvent: true,
      sortOrder: 1,
      hideDueDate: true,
      blockEntryForm: false,
      minDaysFromStart: 0,
      program: {
        id: 'ROSaojkGieB',
      },
      programStageDataElements: [
        {
          id: 'kmzE1H2Vc2b',
          displayInReports: true,
          skipSynchronization: false,
          externalAccess: false,
          renderOptionsAsRadio: false,
          allowFutureDate: false,
          compulsory: false,
          allowProvidedElsewhere: false,
          sortOrder: 1,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          dataElement: {
            id: 'DRFRXS9YGDw',
          },
        },
        {
          id: 'Y4OIrJp8WOA',
          displayInReports: true,
          skipSynchronization: false,
          externalAccess: false,
          renderOptionsAsRadio: false,
          allowFutureDate: false,
          compulsory: false,
          allowProvidedElsewhere: false,
          sortOrder: 2,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          dataElement: {
            id: 'D8uK000mWtr',
          },
        },
      ],
      userGroupAccesses: [
        {
          access: 'rw------',
          userGroupUid: 't7Gi00eBwdQ',
          name: 'Action Tracker users',
          id: 't7Gi00eBwdQ',
        },
      ],
    },
  ],

  programs: [
    {
      id: 'ROSaojkGieB',
      name: 'BNA Linked Action Tracker',
      shortName: 'BNA Linked Action Tracker',
      publicAccess: '--r-----',
      completeEventsExpiryDays: 0,
      ignoreOverdueEvents: false,
      skipOffline: false,
      minAttributesRequiredToSearch: 1,
      displayFrontPageList: true,
      onlyEnrollOnce: true,
      programType: 'WITH_REGISTRATION',
      accessLevel: 'OPEN',
      maxTeiCountToReturn: 0,
      selectIncidentDatesInFuture: false,
      displayIncidentDate: false,
      selectEnrollmentDatesInFuture: false,
      expiryDays: 0,
      useFirstStageDuringRegistration: false,
      trackedEntityType: {
        id: 'WQLx9VNVeZU',
      },

      programTrackedEntityAttributes: [
        {
          id: 'LecLymPquue',
          name: 'BNA Linked Action Tracker BNA Reference',
          mandatory: false,
          shortName: 'BNA Reference',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'TEXT',
          searchable: true,
          displayInList: false,
          sortOrder: 1,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          trackedEntityAttribute: {
            id: 'blOw6mjuv6j',
          },
        },
        {
          id: 'DfT0JC0VKA3',
          name: 'BNA Linked Action Tracker Action Description',
          mandatory: true,
          shortName: 'Action Description',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'LONG_TEXT',
          searchable: false,
          displayInList: true,
          sortOrder: 2,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          trackedEntityAttribute: {
            id: 'dhr6wl8F7So',
          },
        },
        {
          id: 'ydN3ekUUT2m',
          name: 'BNA Linked Action Tracker Start Date',
          mandatory: true,
          shortName: 'Start Date',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'DATE',
          searchable: false,
          displayInList: true,
          sortOrder: 3,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          trackedEntityAttribute: {
            id: 'qTXUUntafIX',
          },
        },
        {
          id: 'UPiRHleMEsi',
          name: 'BNA Linked Action Tracker End Date',
          mandatory: false,
          shortName: 'End Date',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'DATE',
          searchable: false,
          displayInList: true,
          sortOrder: 4,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          trackedEntityAttribute: {
            id: 'ge6NMvlcYx5',
          },
        },
        {
          id: 'XajRri3534V',
          name: 'BNA Linked Action Tracker Responsible Person',
          mandatory: true,
          shortName: 'Responsible Person',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'TEXT',
          searchable: false,
          displayInList: true,
          sortOrder: 5,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          trackedEntityAttribute: {
            id: 'AuW5NppdH5e',
          },
        },
        {
          id: 'fzISmkQRgcb',
          name: 'BNA Linked Action Tracker Designation Title',
          mandatory: false,
          shortName: 'Designation Title',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'TEXT',
          searchable: false,
          displayInList: true,
          sortOrder: 6,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          trackedEntityAttribute: {
            id: 'Ua9aBlFUHXb',
          },
        },
        {
          id: 'xh38fmO5BmB',
          name: 'BNA Linked Action Tracker Budget',
          mandatory: false,
          shortName: 'Budget',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'INTEGER_ZERO_OR_POSITIVE',
          searchable: true,
          displayInList: true,
          sortOrder: 7,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          trackedEntityAttribute: {
            id: 'P7qIYtQIeoK',
          },
        },
        {
          id: 'hUaP4U5Wwvj',
          name: 'BNA Linked Action Tracker BNA Target',
          mandatory: false,
          shortName: 'BNA Target',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'PERCENTAGE',
          searchable: true,
          displayInList: true,
          sortOrder: 8,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          trackedEntityAttribute: {
            id: 'knMPFmtAM29',
          },
        },
      ],
      userGroupAccesses: [
        {
          access: 'rwrw----',
          userGroupUid: 't7Gi00eBwdQ',
          name: 'Action Tracker users',
          id: 't7Gi00eBwdQ',
        },
      ],
      programStages: [
        {
          id: 'TppfLBfs95i',
        },
      ],
    },
  ],
};
