export const defaultActionTrackerProgram: any = {
  attributes: [
    {
      id: 'xsOK0ms8YJv',
      name: 'columnMandatory',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: true,
      constantAttribute: false,
      valueType: 'BOOLEAN',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: true,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: true,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,

      translations: [],
      userGroupAccesses: [],
      userAccesses: [],
    },
    {
      id: 'GvW2Wtw6L5l',
      name: 'hasLegend',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: true,
      constantAttribute: false,
      valueType: 'BOOLEAN',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: false,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: false,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,

      translations: [],
      userGroupAccesses: [],
      userAccesses: [],
    },
    {
      id: 'GOcsBWoi35g',
      name: 'isActionStatus',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: true,
      constantAttribute: false,
      valueType: 'BOOLEAN',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: false,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: false,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,

      translations: [],
      userGroupAccesses: [],
      userAccesses: [],
    },
    {
      id: 'e444SAZc6Qg',
      name: 'isRangePeriod',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: false,
      constantAttribute: false,
      valueType: 'BOOLEAN',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: true,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: false,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,

      translations: [],
      userGroupAccesses: [],
      userAccesses: [],
    },
    {
      id: 'ryc6MHoA88m',
      name: 'isActionTrackingColumn',
      indicatorAttribute: false,
      indicatorGroupAttribute: false,
      publicAccess: 'rw------',
      userGroupAttribute: false,
      dataElementAttribute: false,
      constantAttribute: false,
      valueType: 'TRUE_ONLY',
      categoryOptionAttribute: false,
      optionSetAttribute: false,
      sqlViewAttribute: false,
      legendSetAttribute: false,
      trackedEntityAttributeAttribute: true,
      organisationUnitAttribute: false,
      dataSetAttribute: false,
      documentAttribute: false,
      unique: false,
      validationRuleGroupAttribute: false,
      dataElementGroupAttribute: false,
      sectionAttribute: false,
      trackedEntityTypeAttribute: false,
      userAttribute: false,
      mandatory: false,
      categoryOptionGroupAttribute: false,
      programStageAttribute: false,
      programAttribute: false,
      categoryAttribute: false,
      categoryOptionComboAttribute: false,
      categoryOptionGroupSetAttribute: false,
      validationRuleAttribute: false,
      programIndicatorAttribute: false,
      organisationUnitGroupAttribute: false,
      dataElementGroupSetAttribute: false,
      organisationUnitGroupSetAttribute: false,
      optionAttribute: false,

      translations: [],
      userGroupAccesses: [],
      userAccesses: [],
    },
  ],
  userGroups: [
    {
      code: 'Action Tracker users',
      created: '2020-01-22T11:56:37.957',
      lastUpdated: '2020-05-04T14:06:09.298',
      name: 'Action Tracker users',
      id: 't7Gi00eBwdQ',
      publicAccess: 'rw------',
      userGroupAccesses: [],
      attributeValues: [],

      managedGroups: [],
      translations: [],
      userAccesses: [],
    },
  ],
  trackedEntityAttributes: [
    {
      id: 'Ua9aBlFUHXb',
      name: 'Designation Title',
      shortName: 'Designation Title',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,

      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
      userAccesses: [],
      legendSets: [],
    },
    {
      code: 'BNA_REF',
      id: 'blOw6mjuv6j',
      name: 'BNA Reference',
      shortName: 'BNA Reference',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,

      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
      userAccesses: [],
      legendSets: [],
    },
    {
      id: 'dhr6wl8F7So',
      name: 'Action Description',
      shortName: 'Action Description',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'LONG_TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,

      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
      userAccesses: [],
      legendSets: [],
    },
    {
      id: 'qTXUUntafIX',
      name: 'Start Date',
      shortName: 'Start Date',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'DATE',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,

      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'e444SAZc6Qg',
          },
        },
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
      userAccesses: [],
      legendSets: [],
    },
    {
      id: 'P7qIYtQIeoK',
      name: 'Budget',
      shortName: 'Budget',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,

      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'ryc6MHoA88m',
          },
        },
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
      userAccesses: [],
      legendSets: [],
    },
    {
      id: 'knMPFmtAM29',
      name: 'BNA Target',
      shortName: 'BNA Target',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'NUMBER',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,

      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'ryc6MHoA88m',
          },
        },
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
      userAccesses: [],
      legendSets: [],
    },
    {
      id: 'ge6NMvlcYx5',
      name: 'End Date',
      shortName: 'End Date',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'DATE',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,

      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          value: 'false',
          attribute: {
            id: 'e444SAZc6Qg',
          },
        },
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
      userAccesses: [],
      legendSets: [],
    },
    {
      id: 'AuW5NppdH5e',
      name: 'Responsible Person',
      shortName: 'Responsible Person',
      aggregationType: 'NONE',
      programScope: false,
      displayInListNoProgram: false,
      publicAccess: 'rw------',
      pattern: '',
      skipSynchronization: false,
      generated: false,
      displayOnVisitSchedule: false,
      valueType: 'TEXT',
      orgunitScope: false,
      confidential: false,
      unique: false,
      inherit: false,

      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
      userAccesses: [],
      legendSets: [],
    },
  ],
  categoryCombos: [
    {
      code: 'default',
      name: 'default',
      id: 'bjDvmb4bfuf',
      dataDimensionType: 'DISAGGREGATION',
      publicAccess: 'rw------',
      skipTotal: false,
      userGroupAccesses: [],
      translations: [],
      userAccesses: [],
      categories: [
        {
          id: 'GLevLNI9wkl',
        },
      ],
    },
  ],
  programTrackedEntityAttributes: [
    {
      id: 'UPiRHleMEsi',
      mandatory: false,
      searchable: false,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 4,
      program: {
        id: 'ROSaojkGieB',
      },
      trackedEntityAttribute: {
        id: 'ge6NMvlcYx5',
      },
      programTrackedEntityAttributeGroups: [],
    },
    {
      id: 'LecLymPquue',
      mandatory: false,
      searchable: true,
      renderOptionsAsRadio: false,
      displayInList: false,
      sortOrder: 1,
      program: {
        id: 'ROSaojkGieB',
      },
      trackedEntityAttribute: {
        id: 'blOw6mjuv6j',
      },
      programTrackedEntityAttributeGroups: [],
    },
    {
      id: 'XajRri3534V',
      mandatory: true,
      searchable: false,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 5,
      program: {
        id: 'ROSaojkGieB',
      },
      trackedEntityAttribute: {
        id: 'AuW5NppdH5e',
      },
      programTrackedEntityAttributeGroups: [],
    },
    {
      id: 'xh38fmO5BmB',
      mandatory: false,
      searchable: true,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 7,
      program: {
        id: 'ROSaojkGieB',
      },
      trackedEntityAttribute: {
        id: 'P7qIYtQIeoK',
      },
      programTrackedEntityAttributeGroups: [],
    },
    {
      id: 'hUaP4U5Wwvj',
      mandatory: false,
      searchable: true,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 8,
      program: {
        id: 'ROSaojkGieB',
      },
      trackedEntityAttribute: {
        id: 'knMPFmtAM29',
      },
      programTrackedEntityAttributeGroups: [],
    },
    {
      id: 'DfT0JC0VKA3',
      mandatory: true,
      searchable: false,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 2,
      program: {
        id: 'ROSaojkGieB',
      },
      trackedEntityAttribute: {
        id: 'dhr6wl8F7So',
      },
      programTrackedEntityAttributeGroups: [],
    },
    {
      id: 'ydN3ekUUT2m',
      mandatory: true,
      searchable: false,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 3,
      program: {
        id: 'ROSaojkGieB',
      },
      trackedEntityAttribute: {
        id: 'qTXUUntafIX',
      },
      programTrackedEntityAttributeGroups: [],
    },
    {
      id: 'fzISmkQRgcb',
      mandatory: false,
      searchable: false,
      renderOptionsAsRadio: false,
      displayInList: true,
      sortOrder: 6,
      program: {
        id: 'ROSaojkGieB',
      },
      trackedEntityAttribute: {
        id: 'Ua9aBlFUHXb',
      },
      programTrackedEntityAttributeGroups: [],
    },
  ],
  programStages: [
    {
      id: 'TppfLBfs95i',
      name: 'Action Status',
      allowGenerateNextVisit: false,
      executionDateLabel: 'Review Date',
      preGenerateUID: false,
      publicAccess: '--r-----',
      openAfterEnrollment: false,
      repeatable: true,
      remindCompleted: false,
      displayGenerateEventBox: true,
      generatedByEnrollmentDate: false,
      validationStrategy: 'ON_COMPLETE',
      autoGenerateEvent: true,
      sortOrder: 1,
      hideDueDate: true,
      blockEntryForm: false,
      minDaysFromStart: 0,
      program: {
        id: 'ROSaojkGieB',
      },

      notificationTemplates: [],
      programStageDataElements: [
        {
          id: 'kmzE1H2Vc2b',
          displayInReports: true,
          skipSynchronization: false,
          externalAccess: false,
          renderOptionsAsRadio: false,
          allowFutureDate: false,
          compulsory: false,
          allowProvidedElsewhere: false,
          sortOrder: 1,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          programStage: {
            id: 'TppfLBfs95i',
          },
          dataElement: {
            id: 'DRFRXS9YGDw',
          },
          favorites: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: [],
        },
        {
          id: 'Y4OIrJp8WOA',
          displayInReports: true,
          skipSynchronization: false,
          externalAccess: false,
          renderOptionsAsRadio: false,
          allowFutureDate: false,
          compulsory: false,
          allowProvidedElsewhere: false,
          sortOrder: 2,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          programStage: {
            id: 'TppfLBfs95i',
          },
          dataElement: {
            id: 'D8uK000mWtr',
          },
          favorites: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: [],
        },
      ],
      translations: [],
      userGroupAccesses: [
        {
          access: 'rw------',
          userGroupUid: 't7Gi00eBwdQ',
          displayName: 'Action Tracker users',
          id: 't7Gi00eBwdQ',
        },
      ],
      attributeValues: [],
      userAccesses: [],
      programStageSections: [],
    },
  ],
  programStageDataElements: [
    {
      id: 'kmzE1H2Vc2b',
      displayInReports: true,
      skipSynchronization: false,
      renderOptionsAsRadio: false,
      compulsory: false,
      allowProvidedElsewhere: false,
      sortOrder: 1,
      allowFutureDate: false,
      programStage: {
        id: 'TppfLBfs95i',
      },
      dataElement: {
        id: 'DRFRXS9YGDw',
      },
    },
    {
      id: 'Y4OIrJp8WOA',
      displayInReports: true,
      skipSynchronization: false,
      renderOptionsAsRadio: false,
      compulsory: false,
      allowProvidedElsewhere: false,
      sortOrder: 2,
      allowFutureDate: false,
      programStage: {
        id: 'TppfLBfs95i',
      },
      dataElement: {
        id: 'D8uK000mWtr',
      },
    },
  ],
  trackedEntityTypes: [
    {
      name: 'Action',
      id: 'WQLx9VNVeZU',
      publicAccess: 'rwrw----',
      description: 'Action Item',
      maxTeiCountToReturn: 0,
      allowAuditLog: false,
      featureType: 'NONE',
      minAttributesRequiredToSearch: 1,

      userGroupAccesses: [],
      attributeValues: [],
      trackedEntityTypeAttributes: [],
      translations: [],
      userAccesses: [],
    },
  ],
  categories: [
    {
      code: 'default',
      name: 'default',
      id: 'GLevLNI9wkl',
      dataDimensionType: 'DISAGGREGATION',
      publicAccess: 'rw------',
      dataDimension: false,
      userGroupAccesses: [],
      attributeValues: [],
      translations: [],
      userAccesses: [],
      categoryOptions: [
        {
          id: 'xYerKDKCefk',
        },
      ],
    },
  ],
  dataElements: [
    {
      id: 'DRFRXS9YGDw',
      name: 'Action Tracker : Action Status',
      shortName: 'Action Tracker : Action Status',
      aggregationType: 'NONE',
      domainType: 'TRACKER',
      publicAccess: 'rw------',
      description: 'Field to capture the status of the action execution',
      valueType: 'TEXT',
      formName: 'Action Status',
      zeroIsSignificant: false,
      categoryCombo: {
        id: 'bjDvmb4bfuf',
      },

      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'GOcsBWoi35g',
          },
        },
        {
          value: 'true',
          attribute: {
            id: 'GvW2Wtw6L5l',
          },
        },
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
      userAccesses: [],
      legendSets: [],
      aggregationLevels: [],
    },
    {
      id: 'D8uK000mWtr',
      name: 'Action Tracker : Comments',
      shortName: 'Action Tracker : Comments',
      aggregationType: 'NONE',
      domainType: 'TRACKER',
      publicAccess: 'rw------',
      description: 'Field to capture the action comments',
      valueType: 'LONG_TEXT',
      formName: 'Action Comments',
      zeroIsSignificant: false,
      categoryCombo: {
        id: 'bjDvmb4bfuf',
      },

      translations: [],
      userGroupAccesses: [],
      attributeValues: [
        {
          value: 'true',
          attribute: {
            id: 'xsOK0ms8YJv',
          },
        },
      ],
      userAccesses: [],
      legendSets: [],
      aggregationLevels: [],
    },
  ],
  categoryOptions: [
    {
      code: 'default',
      name: 'default',
      id: 'xYerKDKCefk',
      publicAccess: 'rwrw----',
      userGroupAccesses: [],
      attributeValues: [],
      translations: [],
      userAccesses: [],
      organisationUnits: [],
    },
  ],
  categoryOptionCombos: [
    {
      code: 'default',
      name: 'default',
      id: 'HllvX50cXC0',
      ignoreApproval: false,
      categoryCombo: {
        id: 'bjDvmb4bfuf',
      },
      translations: [],
      attributeValues: [],
      categoryOptions: [
        {
          id: 'xYerKDKCefk',
        },
      ],
    },
  ],
  programs: [
    {
      id: 'ROSaojkGieB',
      name: 'Action Tracker v1',
      shortName: 'Action Tracker v1',
      publicAccess: '--r-----',
      completeEventsExpiryDays: 0,
      ignoreOverdueEvents: false,
      skipOffline: false,
      minAttributesRequiredToSearch: 1,
      displayFrontPageList: true,
      onlyEnrollOnce: true,
      programType: 'WITH_REGISTRATION',
      accessLevel: 'OPEN',
      version: 26,
      maxTeiCountToReturn: 0,
      selectIncidentDatesInFuture: false,
      displayIncidentDate: false,
      selectEnrollmentDatesInFuture: false,
      expiryDays: 0,
      useFirstStageDuringRegistration: false,
      categoryCombo: {
        id: 'bjDvmb4bfuf',
      },

      trackedEntityType: {
        id: 'WQLx9VNVeZU',
      },

      programTrackedEntityAttributes: [
        {
          id: 'LecLymPquue',
          name: 'Action Tracker v1 BNA Reference',
          displayName: 'Action Tracker v1 BNA Reference',
          mandatory: false,
          displayShortName: 'Action Tracker v1 BNA Reference',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'TEXT',
          searchable: true,
          displayInList: false,
          sortOrder: 1,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          program: {
            id: 'ROSaojkGieB',
          },
          trackedEntityAttribute: {
            id: 'blOw6mjuv6j',
          },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: [],
        },
        {
          id: 'DfT0JC0VKA3',
          name: 'Action Tracker v1 Action Description',
          displayName: 'Action Tracker v1 Action Description',
          mandatory: true,
          displayShortName: 'Action Tracker v1 Action Description',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'LONG_TEXT',
          searchable: false,
          displayInList: true,
          sortOrder: 2,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          program: {
            id: 'ROSaojkGieB',
          },
          trackedEntityAttribute: {
            id: 'dhr6wl8F7So',
          },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: [],
        },
        {
          id: 'ydN3ekUUT2m',
          name: 'Action Tracker v1 Start Date',
          displayName: 'Action Tracker v1 Start Date',
          mandatory: true,
          displayShortName: 'Action Tracker v1 Start Date',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'DATE',
          searchable: false,
          displayInList: true,
          sortOrder: 3,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          program: {
            id: 'ROSaojkGieB',
          },
          trackedEntityAttribute: {
            id: 'qTXUUntafIX',
          },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: [],
        },
        {
          id: 'UPiRHleMEsi',
          name: 'Action Tracker v1 End Date',
          displayName: 'Action Tracker v1 End Date',
          mandatory: false,
          displayShortName: 'Action Tracker v1 End Date',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'DATE',
          searchable: false,
          displayInList: true,
          sortOrder: 4,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          program: {
            id: 'ROSaojkGieB',
          },
          trackedEntityAttribute: {
            id: 'ge6NMvlcYx5',
          },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: [],
        },
        {
          id: 'XajRri3534V',
          name: 'Action Tracker v1 Responsible Person',
          displayName: 'Action Tracker v1 Responsible Person',
          mandatory: true,
          displayShortName: 'Action Tracker v1 Responsible Person',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'TEXT',
          searchable: false,
          displayInList: true,
          sortOrder: 5,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          program: {
            id: 'ROSaojkGieB',
          },
          trackedEntityAttribute: {
            id: 'AuW5NppdH5e',
          },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: [],
        },
        {
          id: 'fzISmkQRgcb',
          name: 'Action Tracker v1 Designation Title',
          displayName: 'Action Tracker v1 Designation Title',
          mandatory: false,
          displayShortName: 'Action Tracker v1 Designation Title',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'TEXT',
          searchable: false,
          displayInList: true,
          sortOrder: 6,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          program: {
            id: 'ROSaojkGieB',
          },
          trackedEntityAttribute: {
            id: 'Ua9aBlFUHXb',
          },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: [],
        },
        {
          id: 'xh38fmO5BmB',
          name: 'Action Tracker v1 Budget',
          displayName: 'Action Tracker v1 Budget',
          mandatory: false,
          displayShortName: 'Action Tracker v1 Budget',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'TEXT',
          searchable: true,
          displayInList: true,
          sortOrder: 7,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          program: {
            id: 'ROSaojkGieB',
          },
          trackedEntityAttribute: {
            id: 'P7qIYtQIeoK',
          },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: [],
        },
        {
          id: 'hUaP4U5Wwvj',
          name: 'Action Tracker v1 BNA Target',
          displayName: 'Action Tracker v1 BNA Target',
          mandatory: false,
          displayShortName: 'Action Tracker v1 BNA Target',
          externalAccess: false,
          renderOptionsAsRadio: false,
          valueType: 'NUMBER',
          searchable: true,
          displayInList: true,
          sortOrder: 8,
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          program: {
            id: 'ROSaojkGieB',
          },
          trackedEntityAttribute: {
            id: 'knMPFmtAM29',
          },
          favorites: [],
          programTrackedEntityAttributeGroups: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: [],
        },
      ],
      notificationTemplates: [],
      translations: [],
      userGroupAccesses: [
        {
          access: 'rwrw----',
          userGroupUid: 't7Gi00eBwdQ',
          displayName: 'Action Tracker users',
          id: 't7Gi00eBwdQ',
        },
      ],
      programSections: [],
      attributeValues: [],
      programStages: [
        {
          id: 'TppfLBfs95i',
        },
      ],
      userAccesses: [],
    },
  ],
};
